# Generated by Django 2.1.7 on 2019-04-22 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_logincredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logincredential',
            name='username',
        ),
    ]
