# Generated by Django 2.1.7 on 2019-04-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_remove_logincredential_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincredential',
            name='firstname',
            field=models.CharField(default='firstNameDefault', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logincredential',
            name='lastname',
            field=models.CharField(default='lastNameDefault', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logincredential',
            name='username',
            field=models.CharField(default='defaultUserName', max_length=10),
            preserve_default=False,
        ),
    ]
