# Generated by Django 2.2 on 2019-05-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_auto_20190421_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincredential',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
